// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbeWaKRll8Sf2nhvuofWW3FRWkGgGYuA',
    appId: '1:620524649430:web:your_web_app_id',
    messagingSenderId: '620524649430',
    projectId: 'preachepro',
    authDomain: 'preachepro.firebaseapp.com',
    storageBucket: 'preachepro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwbeWaKRll8Sf2nhvuofWW3FRWkGgGYuA',
    appId: '1:620524649430:android:fd3bceb914859d3229c277',
    messagingSenderId: '620524649430',
    projectId: 'preachepro',
    storageBucket: 'preachepro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJkeEKphhv5zOTzveqS1yQzkagNXvUHI',
    appId: '1:620524649430:ios:671ec5104c10f7e029c277',
    messagingSenderId: '620524649430',
    projectId: 'preachepro',
    iosBundleId: 'com.example.preacherpro',
    storageBucket: 'preachepro.firebasestorage.app',
  );
}
